{% set name = "spimagine" %}
{% set setupdata = load_setup_py_data() %}

package:
  name: {{ name }}
  {% if environ.get('BRANCH') == "master" %}
  version: {{ setupdata.get('version') }}
  {% else %}
  version: "{{ GIT_DESCRIBE_TAG }}_{{ GIT_BUILD_STR }}"
  {% endif %}

source:
  git_tag: conda
  git_url: https://github.com/tlambert03/spimagine
  git_rev: "{{ environ.get('BRANCH') }}"


build:
  number: 0
  string: 'py{{ PY_VER|replace(".", "") }}_{{ PKG_BUILDNUM }}'
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    {% for key, list in setupdata.get('entry_points').items() %}
      {% for item in list %}
    - {{item}}
      {% endfor %}
    {% endfor %}


requirements:
  build:
    - python {{ python }}
    - setuptools
  run:
    - python {{ python }}
    - numpy {{ numpy }}
    - gputools >=0.2.6
    - scipy >=1.1.0
    - imageio >=2.3.0
    - pyqt >=5.9.2
    - pyopengl
    - pyopengl-accelerate # [not linux]
    - sortedcontainers >=1.5.10
    - configparser # [py2k]

test:
  imports:
    - spimagine
  requires:
    - nose
    - matplotlib
    - termcolor
    - scikit-image
  commands:
    - nosetests -v tests
#    - spimagine

about:
  home: {{ setupdata.get('url') }}
  license: {{ setupdata.get('license') }}
  license_file: LICENSE.txt
  summary: {{ setupdata.get('description') }}